// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class Address
    {
        public Address()
        {
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public int? UserId { get; set; }
        public string NameUser { get; set; }
        public string Telephone { get; set; }
        public string Address1 { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Zipcode { get; set; }
        public string Isused { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}