// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class ManageStock
    {
        public int Id { get; set; }
        public string ProdcutId { get; set; }
        public int? Stock { get; set; }
        public DateTime? Date { get; set; }
        public string TypeManage { get; set; }
        public string Detail { get; set; }

        public virtual Product Prodcut { get; set; }
    }
}