// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class Order
    {
        public Order()
        {
            OrderDetail = new HashSet<OrderDetail>();
            Payment = new HashSet<Payment>();
            TransportDetail = new HashSet<TransportDetail>();
        }

        public string Id { get; set; }
        public int? UserId { get; set; }
        public int? AddressId { get; set; }
        public string Status { get; set; }
        public int? Total { get; set; }
        public DateTime? Date { get; set; }
        public string TransportCode { get; set; }
        public string Isused { get; set; }

        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ICollection<TransportDetail> TransportDetail { get; set; }
    }
}