// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class Product
    {
        public Product()
        {
            ManageStock = new HashSet<ManageStock>();
            OrderDetail = new HashSet<OrderDetail>();
            ProductDetail = new HashSet<ProductDetail>();
            Review = new HashSet<Review>();
        }

        public string Id { get; set; }
        public int? TypeId { get; set; }
        public string Name { get; set; }
        public int? Price { get; set; }
        public int? Stock { get; set; }
        public int? StockSell { get; set; }
        public string Detail { get; set; }
        public string TypeSeed { get; set; }
        public string LevelCoffee { get; set; }
        public string Isused { get; set; }

        public virtual TypeProduct Type { get; set; }
        public virtual ICollection<ManageStock> ManageStock { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}