// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class ReviewDetail
    {
        public string Id { get; set; }
        public int ReviewId { get; set; }
        public string Img { get; set; }

        public virtual Review Review { get; set; }
    }
}