// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class Review
    {
        public Review()
        {
            ReviewDetail = new HashSet<ReviewDetail>();
        }

        public int Id { get; set; }
        public int? UserId { get; set; }
        public string ProductId { get; set; }
        public string Comments { get; set; }
        public int? Star { get; set; }
        public DateTime? Date { get; set; }

        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ReviewDetail> ReviewDetail { get; set; }
    }
}