// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class TransportDetail
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string Status { get; set; }
        public string Detail { get; set; }
        public string OrderId { get; set; }

        public virtual Order Order { get; set; }
    }
}