// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Back3.Models.Data
{
    public partial class User
    {
        public User()
        {
            Address = new HashSet<Address>();
            Order = new HashSet<Order>();
            Review = new HashSet<Review>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public DateTime? DateReg { get; set; }
        public string Isused { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}